---
- hosts: all
  become: true
  tasks:
    - name: Install Softwares
      yum: name="{{item}}" state=present
      with_items:
       - git
       - unzip
       - tree
       - unzip       
...  
